version: '3.9'
services:
  postgresql:
    image: postgres:16
    container_name: parking-psql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  rabbitmq:
     image: rabbitmq:3-management
     container_name: parking-mq
     ports:
      - "5672:5672" 
      - "15672:15672"
     environment:
        RABBITMQ_DEFAULT_USER: "user"
        RABBITMQ_DEFAULT_PASS: "password"
  localstack:
      image: localstack/localstack:latest
      ports:
        - "4566:4566"  
        - "8080:8080"  
      environment:
        - SERVICES=s3,dynamodb,logs
        - DEBUG=1
        - DOCKER_HOST=unix:///var/run/docker.sock
        - AWS_ACCESS_KEY_ID=test-key
        - AWS_SECRET_ACCESS_KEY=test-secret
        - ALLOW_NONSTANDARD_REGIONS=1 
      volumes:
        - ./localstack:/var/lib/localstack  
        - /var/run/docker.sock:/var/run/docker.sock
        - ./script/dynamodb/init-dynamodb.sh:/docker-entrypoint-initaws.d/init-dynamodb.sh
